const trainingResult = [
    "input: Tôi muốn biết thêm thông tin tuyến xe",
    "output: Bạn có thể tìm kiếm về thông tin của tuyến xe thông qua phần Header của Webiste",
    "input: Tôi muốn biết thêm thông tin tuyến xe",
    "output: Bạn có thể tìm kiếm về thông tin của tuyến xe thông qua phần Header của Website.",
    "input: I want to have a information about bus route",
    "output: You can find information about bus routes through the Header of the Website.  Please provide me with the website you're referring to, and I can try to help you find the information you're looking for!",
    "input: I want to have a information about bus route",
    "output: You can find information about bus routes through the Header of the Website.  Please provide me with the website you're referring to, and I can try to help you find the information you're looking for!",
    "input: Can I have information about bus route",
    "output: You can find information about bus routes through the Header of the Website.  Please provide me with the website you're referring to, and I can try to help you find the information you're looking for!",
    "input: Give me information regarding bus route",
    "output: You can find information about bus routes through the Header of the Website. Please provide me with the website you're referring to, and I can try to help you find the information you're looking for!",
    "input: I want to have a information about bus route",
    "output: You can find information about bus routes through the Header of the Website.  Please provide me with the website you're referring to, and I can try to help you find the information you're looking for!",
    "input: Tôi muốn biết về lịch trình",
    "output: Bạn có thể tìm thấy phần lịch trình ở Header Website",
    "input: Tôi muốn xem thông tin lịch trình của xe",
    "output: Bạn có thể tìm thấy phần lịch trình ở Header Website, nhớ đặt vé ủng hộ mình nhé",
    "input: Tôi muốn biết về lịch trình",
    "output: Bạn có thể tìm thấy phần lịch trình ở Header Website.",
    "input: Tôi muốn xem thông tin tuyến xe thì xem ở đâu",
    "output: Phần Header của website",
    "input: Tôi muốn biết thông tin lịch trình của xe",
    "output: Bạn có thể tìm thấy phần lịch trình ở Header Website, nhớ đặt vé ủng hộ mình nhé.",
    "input: Thông tin tuyến xe",
    "output: Bạn hãy xem phần Header của Website",
    "input: Lịch trình của xe",
    "output: Hãy xem danh sách lịch trình ở phần Header, và nhớ hãy mua vé ủng hộ mình nhé",
    "input: Tôi muốn đặt vé xe",
    "output: Hãy vào phần lịch trình của Header để xem bạn muốn mua vé của chuyến xe nào nhé",
    "input: Xem thêm thông tin",
    "output: Bạn có thể vào phần Header hoặc thanh tác vụ để xem các thông tin chi tiết nhé",
    "input: Chi tiết tuyến xe",
    "output: Bạn có thể xem nó ở phần Header, nó sẽ hiển thị cụ thể chi tiết bao gồm danh sách các trạm cũng như bản đồ chi tiết",
    "input: Tìm đường",
    "output: Bạn vào phần Header và chọn tìm đường, sau đó cung cấp điểm đi và đích đến giúp mình nhé",
    "input: Tuyến xe chi tiết",
    "output: Bạn có thể xem chi tiết tuyến xe tại phần Header của Website. Nó sẽ hiển thị danh sách các trạm và bản đồ chi tiết.",
    "input: Chỉ đường",
    "output: Bạn vào phần Header và chọn tìm đường, sau đó cung cấp điểm đi và đích đến giúp mình nhé",
    "input: Tôi muốn di chuyển từ trạm này đến trạm khác thì phải làm sao",
    "output: Bạn vào phần Header và chọn tìm đường, sau đó cung cấp điểm đi và đích đến giúp mình nhé",
    "input: Tôi có thắc mắc cần giải đáp",
    "output: Hãy vào ngăn kéo tác vụ, tìm đến phần Chat với Admin và đặt câu hỏi giúp mình nhé",
    "input: Tôi muốn đi từ trạm A tới trạm B thì phải làm gì",
    "output: Bạn có thể tìm đường trong phần Header, hãy cung cấp cho mình điểm đi và đích đến để mình tìm đường cho bạn nhé.",
    "input: Tôi có câu hỏi",
    "output: Hãy vào ngăn kéo tác vụ và đặt câu hỏi này tới Admin giúp mình nhé",
    "input: Giá vé",
    "output: Hãy xem danh sách lịch trình ở phần Header, xem giá của chuyến xe  và nhớ hãy mua vé ủng hộ mình nhé",
    "input: Liên hệ",
    "output: Vui lòng liên hệ qua email 2151053052quy@ou.edu.vn",
    "input: Mua vé",
    "output: Hãy xem danh sách lịch trình ở phần Header, xem giá của chuyến xe  và nhớ hãy mua vé ủng hộ mình nhé",
    "input: Đặt vé",
    "output: Hãy xem danh sách lịch trình ở phần Header, xem giá của chuyến xe  và nhớ hãy mua vé ủng hộ mình nhé",
    "input: Bản đồ",
    "output: Hãy vào xem thông tin tuyến xe để có thể xem được bản đồ nhé",
    "input: Danh sách trạm",
    "output: Danh sách trạm nằm trong thông tin chi tiết của từng tuyến xe",
    "input: Xin chào",
    "output: Xin chào bạn, mình là Nguyễn Thi Quý, quản trị viên của BusMap",
    "input: Hello",
    "output: Xin chào bạn, mình là Nguyễn Thi Quý, quản trị viên của BusMap",
    "input: Thanh toán",
    "output: Hệ thống của mình thanh toán vé xe thông qua dịch vụ ZaloPay",
    "input: Thông tin về tuyến xe A",
    "output: Hãy xem nó trong phần Header tuyến xe nhé",
    "input: Tuyến đường",
    "output: Xem nó trong mục tuyến xe của Header Website giúp mình nhé",
    "input: Bạn có thể giúp tôi được không",
    "output: Tất nhiên rồi, hãy đặt câu hỏi bất kì tôi sẽ trợ giúp bạn",
    "input: Tạm biệt",
    "output: Chào tạm biệt, chúc bạn có trải nghiệm tốt nhất",
    "input: Quãng đường",
    "output: Bạn xem quãng đường từ trạm tới trạm thông qua mục tìm đường giúp mình nhé",
    "input: Tin tức",
    "output: Bạn có thể xem tin tức mới nhất được cập nhật thông qua mục Blogs của Header nhé",
    "input: Blogs",
    "output: Bạn xem blog mà mình đăng trên hệ thống nhé",
    "input: Blog",
    "output: Nhiều bài Blog được thêm và cập nhật trên hệ thống",
    "input: Đăng ký người dùng",
    "output: Bạn chọn mục đăng ký và cung cấp thông tin cá nhân để tạo mới tài khoản nhé",
    "input: Đăng ký",
    "output: Bạn chọn mục đăng ký và cung cấp thông tin cá nhân để tạo mới tài khoản nhé",
    "input: Đặt ghế",
    "output: Vui lòng đặt ghế trong mục chuyến xe để xem lịch trình nào phù hợp với bạn nhất nhé",
    "input: Tôi muốn đi tới trạm Cộng Hoà thì phải làm sao",
    "output: Bạn có thể tìm đường trong phần Header của Website, hãy cung cấp cho mình điểm đi và đích",
    "input: ",
    "output: ",
  ]

module.exports = trainingResult